" ************
" 	hp vimrc			 
" ************


" *** Pathogen
execute pathogen#infect()
filetype plugin on


" *** Clang use in ycm
let g:ycm_global_ycm_extra_conf = "~/.vim/ycm_extra_conf.py"


" *** VIM Set
if has("syntax")
	syntax on
endif

"set bs=indent,eol,start		"Use backspace
set autoindent
set background=light	"Background color dark or light
set encoding=utf-8	"Encoding Type utf-8
set hlsearch		"Highlight search
set ignorecase		"Search case
set nocompatible		"Window size
set number
set ruler
set showcmd		"Show command in status line.
set title
set ts=4	"Tab 4


" *** Key mapping
let mapleader = ","

noremap ` <ESC>
noremap \` `
noremap <leader>n :cnext<CR>
noremap <leader>m :cprevious<CR>
noremap <leader>c :cclose<CR>
noremap zk :wincmd k<CR>
noremap zl :wincmd l<CR>
noremap zh :wincmd h<CR>
noremap zj :wincmd j<CR>
noremap z\ :NERDTreeToggle<CR>
noremap z] :TagbarToggle<CR>
noremap zu :up<CR>

noremap te :tabedit 
noremap tn :tabnext<CR>

inoremap ` <ESC>
inoremap \` `
"inoremap ]\ <right>
"inoremap ]\\ <right><right>
"inoremap () ()
"inoremap [] []
"inoremap {} {}
inoremap <. <><left>
inoremap </ </><left>
"inoremap ` ``<left>
"inoremap " ""<left>
"inoremap ( ()<left>
"inoremap [ []<left>
"inoremap { {}<left>
inoremap (<CR> (<CR>)<ESC>O<tab>
inoremap {<CR> {<CR>}<ESC>O<tab>
inoremap \`<CR> `<CR>`<ESC>O

cnoremap ` <ESC>
cnoremap \` `


" *** python keymapping
"noremap <tab> :!python3 %
"inoremap """ """
"inoremap """<CR> """<CR>"""<ESC>O
